version: '3'

services:
    db:
      image: biarms/mysql:5.7
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD}
        MYSQL_DATABASE: ${DATABASE}
        MYSQL_USER: ${USERNAME}
        MYSQL_PASSWORD: ${PASSWORD}
      volumes:
        - "mysqldbdata:/Users/raseel.b/workspace/data"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      links:
        - db:db
      depends_on:
        - db
volumes:
  mysqldbdata:
        
