version: '3'

services:
    db:
      image: postgres:12.14
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: ${PASSWORD} 
        POSTGRES_DB: ${DATABASE}
        POSTGRES_USER: ${USERNAME}
      volumes:
        - "postgresqldata:/Users/raseel.b/workspace/data"

    pgadmin:
      image: dpage/pgadmin4
      restart: always
      ports:
        - 5050:80
      environment:
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_DEFAULT_EMAIL: admin@admin.com

volumes:
  postgresqldata:
        
